### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by MSurojit** [Pyo25/Phonegap-SMS-reception-plugin#6]
Always getting this error message

"Error while checking the SMS support". Tried in emulator and in device

**Comment by PrabakarKaruppasamy** [comment]
Same error am also facing??? Any help to resolve this issue.. am using Moto E android kitkat 4.4.4 version....

**Comment by Pyo25** [comment]
Hi @PrabakarKaruppasamy ,

This plugin is not supported anymore. But feel free to fix it & contribute. I'll be happy to review & merge the changes.

Regards
